/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f411_base.h"
#include "gpio_driver.h"
#include "gpio_driver_interrupt.h"

void EXTI0_IRQHandler(void); //button_pressed_callback

// LED Configuration
gpio_config_t led_config = {
    .port = GPIOC,
    .pin = 13,
    .mode = GPIO_MODE_OUTPUT,
    .output_type = GPIO_OTYPE_PUSH_PULL,
    .speed = GPIO_SPEED_LOW,
    .pull = GPIO_PULL_NONE
};

// Button Configuration with Interrupt
gpio_config_t button_config = {
        .port = GPIOA,
        .pin = 0,
        .mode = GPIO_MODE_INPUT,
        .pull = GPIO_PULL_UP
};


int main(void)
{
    // Initialize LED
    gpio_init(&led_config);
    gpio_init(&button_config);
    // Initialize button with interrupt
//    gpio_interrupt_init(&button_config);
    /* Loop forever */
	for(;;){
		gpio_write_pin(led_config.port, led_config.pin, 1);
		for(volatile int i = 0; i < 10000; i++);

		if( gpio_read_pin(button_config.port, button_config.pin)){
			gpio_toggle_pin(led_config.port, led_config.pin);
		}
	}
}


//// Button Configuration with Interrupt
//gpio_interrupt_config_t button_config = {
//    .gpio_config = {
//        .port = GPIOA,
//        .pin = 0,
//        .mode = GPIO_MODE_INPUT,
//        .pull = GPIO_PULL_UP
//    },
//    .interrupt_enable = 1,
//    .trigger_type = EXTI_TRIGGER_FALLING,
//    .priority = 5,
//    .callback = EXTI0_IRQHandler
//};
//
//// Interrupt Service Routine
//void EXTI0_IRQHandler(void) {
//    // Check if EXTI0 triggered the interrupt
//    if (EXTI->PR & EXTI_PR_PR0) {
//        // Clear the pending bit
//        EXTI->PR |= EXTI_PR_PR0;
//
//        // Set flag for main loop
//        gpio_toggle_pin(GPIOC, 13);
//
//        // Optional: Add debouncing delay
//        for (volatile int i = 0; i < 10000; i++);
//    }
//}
